export default [
    {
        name: "Acácia",
        devices: [
            { ip: "10.0.27.1", type: "internet", alert: false, online: true },
            { ip: "10.0.27.3", type: "voz", alert: false, online: true },
            { ip: "10.0.27.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.27.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.27.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.27.32", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Albatroz",
        devices: [
            { ip: "10.0.56.1", type: "internet", alert: false, online: true },
            { ip: "10.0.56.5", type: "voz", alert: false, online: true },
            { ip: "10.0.56.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.56.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.56.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.56.32", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Alfredo de Abreu",
        devices: [
            { ip: "10.0.120.1", type: "internet", alert: false, online: true },
            { ip: "10.0.120.3", type: "voz", alert: false, online: true },
            { ip: "10.0.120.4", type: "voz", alert: false, online: true },
            { ip: "10.0.120.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.120.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.120.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.120.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.120.34", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Alice Neffa",
        devices: [
            { ip: "10.0.103.1", type: "internet", alert: false, online: true },
            { ip: "10.0.103.3", type: "voz", alert: false, online: true },
            { ip: "10.0.103.4", type: "voz", alert: false, online: true },
            { ip: "10.0.103.6", type: "voz", alert: false, online: true },
            { ip: "10.0.103.8", type: "voz", alert: false, online: true },
            { ip: "10.0.103.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.103.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.103.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.103.22", type: "jfl", alert: false, online: true },
            { ip: "10.0.103.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.103.33", type: "acesso", alert: false, online: true },
            { ip: "10.0.103.35", type: "acesso", alert: false, online: true },
            { ip: "10.0.103.36", type: "acesso", alert: false, online: true },
            { ip: "10.0.103.37", type: "acesso", alert: false, online: true },
            { ip: "10.0.103.38", type: "acesso", alert: false, online: true },
            { ip: "10.0.103.45", type: "acesso", alert: false, online: true },
            { ip: "10.0.103.50", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Capitania",
        devices: [
            { ip: "10.0.49.1", type: "internet", alert: false, online: true },
            { ip: "10.0.49.4", type: "voz", alert: false, online: true },
            { ip: "10.0.49.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.49.21", type: "jfl", alert: false, online: true },
        ],
    },
    {
        name: "Caravellas",
        devices: [
            { ip: "10.0.62.1", type: "internet", alert: false, online: true },
            { ip: "10.0.62.3", type: "voz", alert: false, online: true },
            { ip: "10.0.62.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.62.22", type: "jfl", alert: false, online: true },
            { ip: "10.0.62.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.62.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.62.34", type: "acesso", alert: false, online: true },
            { ip: "10.0.62.35", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Carol Wojtyla",
        devices: [
            { ip: "10.0.77.1", type: "internet", alert: false, online: true },
            { ip: "10.0.77.3", type: "voz", alert: false, online: true },
            { ip: "10.0.77.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.77.13", type: "imagem", alert: false, online: true },
            { ip: "10.0.77.17", type: "imagem", alert: false, online: true },
            { ip: "10.0.77.18", type: "imagem", alert: false, online: true },
            { ip: "10.0.77.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.77.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.77.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.77.33", type: "acesso", alert: false, online: true },
            { ip: "10.0.77.40", type: "acesso", alert: false, online: true },
            { ip: "10.0.77.41", type: "acesso", alert: false, online: true },
            { ip: "10.0.77.42", type: "acesso", alert: false, online: true },
            { ip: "10.0.77.43", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Cavalcante",
        devices: [
            { ip: "10.0.32.1", type: "internet", alert: false, online: true },
            { ip: "10.0.32.2", type: "voz", alert: false, online: true },
            { ip: "10.0.32.4", type: "voz", alert: false, online: true },
            { ip: "10.0.32.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.32.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.32.22", type: "jfl", alert: false, online: true },
            { ip: "10.0.32.31", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Costa Dourada",
        devices: [
            { ip: "10.0.105.1", type: "internet", alert: false, online: true },
            { ip: "10.0.105.4", type: "voz", alert: false, online: true },
            { ip: "10.0.105.8", type: "voz", alert: false, online: true },
            { ip: "10.0.105.9", type: "voz", alert: false, online: true },
            { ip: "10.0.105.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.105.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.105.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.105.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.105.33", type: "acesso", alert: false, online: true },
            { ip: "10.0.105.34", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Debret",
        devices: [
            { ip: "10.0.83.1", type: "internet", alert: false, online: true },
            { ip: "10.0.83.2", type: "voz", alert: false, online: true },
            { ip: "10.0.83.4", type: "voz", alert: false, online: true },
            { ip: "10.0.83.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.83.22", type: "jfl", alert: false, online: true },
            { ip: "10.0.83.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.83.33", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Dom Pedro II",
        devices: [
            { ip: "10.0.112.1", type: "internet", alert: false, online: true },
            { ip: "10.0.112.5", type: "voz", alert: false, online: true },
            { ip: "10.0.112.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.112.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.112.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.112.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.112.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.112.33", type: "acesso", alert: false, online: true },
            { ip: "10.0.112.36", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Espelho D'Água",
        devices: [
            { ip: "10.0.18.1", type: "internet", alert: false, online: true },
            { ip: "10.0.18.5", type: "voz", alert: false, online: true },
            { ip: "10.0.18.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.18.32", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "François de Paule",
        devices: [
            { ip: "10.0.54.1", type: "internet", alert: false, online: true },
            { ip: "10.0.54.2", type: "voz", alert: false, online: true },
            { ip: "10.0.54.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.54.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.54.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.54.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.54.32", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Green Hill",
        devices: [
            { ip: "10.0.10.1", type: "internet", alert: false, online: true },
            { ip: "10.0.10.2", type: "voz", alert: false, online: true },
            { ip: "10.0.10.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.10.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.10.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.10.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.10.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.10.33", type: "acesso", alert: false, online: true },
            { ip: "10.0.10.35", type: "acesso", alert: false, online: true },
            { ip: "10.0.10.36", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Ilhas de Roccas",
        devices: [
            { ip: "10.0.2.1", type: "internet", alert: false, online: true },
            { ip: "10.0.2.4", type: "voz", alert: false, online: true },
            { ip: "10.0.2.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.2.22", type: "jfl", alert: false, online: true },
            { ip: "10.0.2.31", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Junieh",
        devices: [
            { ip: "10.0.85.1", type: "internet", alert: false, online: true },
            { ip: "10.0.85.3", type: "voz", alert: false, online: true },
            { ip: "10.0.85.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.85.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.85.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.85.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.85.33", type: "acesso", alert: false, online: true },
            { ip: "10.0.85.34", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Lubianka",
        devices: [
            { ip: "10.0.13.1", type: "internet", alert: false, online: true },
            { ip: "10.0.13.2", type: "voz", alert: false, online: true },
            { ip: "10.0.13.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.13.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.13.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.13.32", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Maison Suisse",
        devices: [
            { ip: "10.0.17.1", type: "internet", alert: false, online: true },
            { ip: "10.0.17.3", type: "voz", alert: false, online: true },
            { ip: "10.0.17.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.17.22", type: "jfl", alert: false, online: true },
            { ip: "10.0.17.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.17.33", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Malibu",
        devices: [
            { ip: "10.0.72.1", type: "internet", alert: false, online: true },
            { ip: "10.0.72.3", type: "voz", alert: false, online: true },
            { ip: "10.0.72.9", type: "voz", alert: false, online: true },
            { ip: "10.0.72.10", type: "voz", alert: false, online: true },
            { ip: "10.0.72.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.72.18", type: "imagem", alert: false, online: true },
            { ip: "10.0.72.19", type: "imagem", alert: false, online: true },
            { ip: "10.0.72.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.72.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.72.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.72.33", type: "acesso", alert: false, online: true },
            { ip: "10.0.72.34", type: "acesso", alert: false, online: true },
            { ip: "10.0.72.36", type: "acesso", alert: false, online: true },
            { ip: "10.0.72.37", type: "acesso", alert: false, online: true },
            { ip: "10.0.72.39", type: "acesso", alert: false, online: true },
            { ip: "10.0.72.40", type: "acesso", alert: false, online: true },
            { ip: "10.0.72.41", type: "acesso", alert: false, online: true },
            { ip: "10.0.72.42", type: "acesso", alert: false, online: true },
            { ip: "10.0.72.43", type: "acesso", alert: false, online: true },
            { ip: "10.0.72.50", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Mar Cáspio",
        devices: [
            { ip: "10.0.42.1", type: "internet", alert: false, online: true },
            { ip: "10.0.42.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.42.14", type: "imagem", alert: false, online: true },
            { ip: "10.0.42.15", type: "imagem", alert: false, online: true },
            { ip: "10.0.42.22", type: "jfl", alert: false, online: true },
            { ip: "10.0.42.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.42.33", type: "acesso", alert: false, online: true },
            { ip: "10.0.42.34", type: "acesso", alert: false, online: true },
            { ip: "10.0.42.35", type: "acesso", alert: false, online: true },
            { ip: "10.0.42.38", type: "acesso", alert: false, online: true },
            { ip: "10.0.42.39", type: "acesso", alert: false, online: true },
            { ip: "10.0.42.40", type: "acesso", alert: false, online: true },
            { ip: "10.0.42.41", type: "acesso", alert: false, online: true },
            { ip: "10.0.42.42", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Maria Medina",
        devices: [
            { ip: "10.0.53.1", type: "internet", alert: false, online: true },
            { ip: "10.0.53.3", type: "voz", alert: false, online: true },
            { ip: "10.0.53.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.53.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.53.13", type: "imagem", alert: false, online: true },
            { ip: "10.0.53.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.53.41", type: "acesso", alert: false, online: true },
            { ip: "10.0.53.42", type: "acesso", alert: false, online: true },
            { ip: "10.0.53.43", type: "acesso", alert: false, online: true },
            { ip: "10.0.53.44", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Mariner Center",
        devices: [
            { ip: "10.0.23.1", type: "internet", alert: false, online: true },
            { ip: "10.0.23.2", type: "voz", alert: false, online: true },
            { ip: "10.0.23.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.23.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.23.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.23.31", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Maryland",
        devices: [
            { ip: "10.0.41.1", type: "internet", alert: false, online: true },
            { ip: "10.0.41.3", type: "voz", alert: false, online: true },
            { ip: "10.0.41.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.41.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.41.22", type: "jfl", alert: false, online: true },
            { ip: "10.0.41.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.41.33", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Milord",
        devices: [
            { ip: "10.0.45.1", type: "internet", alert: false, online: true },
            { ip: "10.0.45.3", type: "voz", alert: false, online: true },
            { ip: "10.0.45.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.45.22", type: "jfl", alert: false, online: true },
            { ip: "10.0.45.31", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Moinho dos Ventos",
        devices: [
            { ip: "10.0.15.1", type: "internet", alert: false, online: true },
            { ip: "10.0.15.2", type: "voz", alert: false, online: true },
            { ip: "10.0.15.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.15.13", type: "imagem", alert: false, online: true },
            { ip: "10.0.15.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.15.31", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Ocean Reef",
        devices: [
            { ip: "10.0.80.1", type: "internet", alert: false, online: true },
            { ip: "10.0.80.2", type: "voz", alert: false, online: true },
            { ip: "10.0.80.3", type: "voz", alert: false, online: true },
            { ip: "10.0.80.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.80.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.80.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.80.32", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Pedra Azul",
        devices: [
            { ip: "10.0.119.1", type: "internet", alert: false, online: true },
            { ip: "10.0.119.3", type: "voz", alert: false, online: true },
            { ip: "10.0.119.6", type: "voz", alert: false, online: true },
            { ip: "10.0.119.8", type: "voz", alert: false, online: true },
            { ip: "10.0.119.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.119.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.119.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.119.22", type: "jfl", alert: false, online: true },
            { ip: "10.0.119.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.119.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.119.33", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Ponta Negra",
        devices: [
            { ip: "10.0.22.1", type: "internet", alert: false, online: true },
            { ip: "10.0.22.3", type: "voz", alert: false, online: true },
            { ip: "10.0.22.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.22.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.22.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.22.32", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Port Deauville",
        devices: [
            { ip: "10.0.25.1", type: "internet", alert: false, online: true },
            { ip: "10.0.25.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.25.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.25.21", type: "jfl", alert: false, online: true },
        ],
    },
    {
        name: "Porto Praia",
        devices: [
            { ip: "10.0.55.1", type: "internet", alert: false, online: true },
            { ip: "10.0.55.4", type: "voz", alert: false, online: true },
            { ip: "10.0.55.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.55.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.55.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.55.32", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Portugal",
        devices: [
            { ip: "10.0.24.1", type: "internet", alert: false, online: true },
            { ip: "10.0.24.3", type: "voz", alert: false, online: true },
            { ip: "10.0.24.5", type: "voz", alert: false, online: true },
            { ip: "10.0.24.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.24.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.24.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.24.32", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Rainha Guilhermina",
        devices: [
            { ip: "10.0.74.1", type: "internet", alert: false, online: true },
            { ip: "10.0.74.3", type: "voz", alert: false, online: true },
            { ip: "10.0.74.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.74.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.74.31", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Rs Trade",
        devices: [
            { ip: "10.0.59.1", type: "internet", alert: false, online: true },
            { ip: "10.0.59.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.59.12", type: "imagem", alert: false, online: true },
        ],
    },
    {
        name: "Tambaú",
        devices: [
            { ip: "10.0.86.1", type: "internet", alert: false, online: true },
            { ip: "10.0.86.2", type: "voz", alert: false, online: true },
            { ip: "10.0.86.6", type: "voz", alert: false, online: true },
            { ip: "10.0.86.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.86.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.86.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.86.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.86.33", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Tropical Garden",
        devices: [
            { ip: "10.0.93.1", type: "internet", alert: false, online: true },
            { ip: "10.0.93.3", type: "voz", alert: false, online: true },
            { ip: "10.0.93.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.93.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.93.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.93.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.93.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.93.33", type: "acesso", alert: false, online: true },
            { ip: "10.0.93.34", type: "acesso", alert: false, online: true },
            { ip: "10.0.93.35", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Vila da Praia",
        devices: [
            { ip: "10.0.75.1", type: "internet", alert: false, online: true },
            { ip: "10.0.75.2", type: "voz", alert: false, online: true },
            { ip: "10.0.75.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.75.22", type: "jfl", alert: false, online: true },
            { ip: "10.0.75.32", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Village Santa Inês",
        devices: [
            { ip: "10.0.40.1", type: "internet", alert: false, online: true },
            { ip: "10.0.40.2", type: "voz", alert: false, online: true },
            { ip: "10.0.40.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.40.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.40.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.40.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.40.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.40.33", type: "acesso", alert: false, online: true },
        ],
    },
    {
        name: "Vogue Enseada",
        devices: [
            { ip: "10.0.106.1", type: "internet", alert: false, online: true },
            { ip: "10.0.106.2", type: "voz", alert: false, online: true },
            { ip: "10.0.106.11", type: "imagem", alert: false, online: true },
            { ip: "10.0.106.12", type: "imagem", alert: false, online: true },
            { ip: "10.0.106.13", type: "imagem", alert: false, online: true },
            { ip: "10.0.106.21", type: "jfl", alert: false, online: true },
            { ip: "10.0.106.31", type: "acesso", alert: false, online: true },
            { ip: "10.0.106.32", type: "acesso", alert: false, online: true },
            { ip: "10.0.106.35", type: "acesso", alert: false, online: true },
        ],
    },
];
